{
 "title": "Imaging",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Task queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Tasks" }
   ],
   "targets": [
    {
     "expr": "sum(katsdpcontroller_batch_tasks_started - katsdpcontroller_batch_tasks_done)",
     "legendFormat": "In progress"
    },
    {
     "expr": "sum(katsdpcontroller_batch_tasks_created - katsdpcontroller_batch_tasks_started)",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(katsdpcontroller_batch_tasks_failed[$__range]))"
    }
   ]
  },
  {
   "title": "Skipped",
   "type": "singlestat",
   "description": "Tasks skipped because a prerequisite task failed",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(katsdpcontroller_batch_tasks_skipped[$__range]))"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 21, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(katsdpcontroller_batch_runtime_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Runtime relative to obs time",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 21, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(katsdpcontroller_batch_runtime_rel_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}