{
 "title": "Subarray view",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "sub",
    "label": "Subarray product",
    "query": "label_values(katsdpcontroller_input_heaps_total_status, subarray_product_id)"
   },
   { "name": "time", "label": "Timescale", "query": "10s,30s,1m,2m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Antennas",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(katsdpcontroller_output_n_ants{service=~\"ingest\\\\..*\", subarray_product_id=\"$sub\"})"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(katsdpcontroller_output_n_chans{service=~\"ingest\\\\.sdp_l0\\\\..*\", subarray_product_id=\"$sub\"})"
    }
   ]
  },
  {
   "title": "Int. time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(katsdpcontroller_output_int_time{service=~\"ingest\\\\..*\", subarray_product_id=\"$sub\"})"
    }
   ]
  },
  { "title": "Ingest", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Input rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(katsdpcontroller_input_bytes_total{service=~\"ingest.*\",subarray_product_id=\"$sub\"}[$time]))"
    }
   ]
  },
  {
   "title": "Heaps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 3 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(katsdpcontroller_input_heaps_total{service=~\"ingest.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Good"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_incomplete_heaps_total{service=~\"ingest.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_bad_timestamp_heaps_total{service=~\"ingest.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Bad timestamp"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_no_descriptor_heaps_total{service=~\"ingest.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "No descriptors"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_bad_channel_heaps_total{service=~\"ingest.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Bad channel"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_too_old_heaps_total{service=~\"ingest.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Too old"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_missing_heaps_total{service=~\"ingest.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Missing"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_metadata_heaps_total{service=~\"ingest.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Metadata"
    }
   ]
  },
  {
   "title": "Flag %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(katsdpcontroller_output_flagged_total{subarray_product_id=\"$sub\"}[$time])) / sum(rate(katsdpcontroller_output_vis_total{subarray_product_id=\"$sub\"}[$time]))"
    }
   ]
  },
  {
   "title": "Output rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(katsdpcontroller_output_bytes_total{service=~\"ingest.*\",subarray_product_id=\"$sub\"}[$time]))"
    }
   ]
  },
  { "title": "Calibration", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Input rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(katsdpcontroller_input_bytes_total{service=~\"cal.*\", subarray_product_id=\"$sub\"}[$time]))"
    }
   ]
  },
  {
   "title": "Heaps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(katsdpcontroller_input_heaps_total{service=~\"cal.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Good"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_incomplete_heaps_total{service=~\"cal.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_too_old_heaps_total{service=~\"cal.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Too old"
    }
   ]
  },
  {
   "title": "Free slots",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "katsdpcontroller_free_slots{subarray_product_id=\"$sub\"} / katsdpcontroller_slots{subarray_product_id=\"$sub\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Pipeline time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "katsdpcontroller_pipeline_last_time{subarray_product_id=\"$sub\"} and (katsdpcontroller_pipeline_last_time{subarray_product_id=\"$sub\"} != katsdpcontroller_pipeline_last_time{subarray_product_id=\"$sub\"} offset $__interval)"
    }
   ]
  },
  {
   "title": "Pipeline errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(katsdpcontroller_pipeline_exceptions{subarray_product_id=\"$sub\"})"
    }
   ]
  },
  {
   "title": "Output rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(katsdpcontroller_output_bytes_total{service=~\"cal.*\", subarray_product_id=\"$sub\"}[$time]))"
    }
   ]
  },
  {
   "title": "Pipeline active",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 13 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(katsdpcontroller_pipeline_active{subarray_product_id=\"$sub\"})"
    }
   ]
  },
  { "title": "Vis writer", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Input rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(katsdpcontroller_input_bytes_total{service=~\"vis_writer.*\",subarray_product_id=\"$sub\"}[$time]))"
    }
   ]
  },
  {
   "title": "Heaps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 17 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(katsdpcontroller_input_heaps_total{service=~\"vis_writer.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Good"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_incomplete_heaps_total{service=~\"vis_writer.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_missing_heaps_total{service=~\"vis_writer.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Missing"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_too_old_heaps_total{service=~\"vis_writer.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Too old"
    }
   ]
  },
  {
   "title": "Write speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "delta(katsdpcontroller_output_bytes_total{service=~\"vis_writer\\\\..*\", subarray_product_id=\"$sub\"}[$time]) / delta(katsdpcontroller_output_seconds_total{service=~\"vis_writer\\\\..*\", subarray_product_id=\"$sub\"}[$time])",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "rate(katsdpcontroller_output_bytes_total{service=~\"vis_writer\\\\..*\", subarray_product_id=\"$sub\"}[$time])",
     "legendFormat": "{{service}} (overall)"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written{instance=~\"fwr.*\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}  (physical)"
    }
   ]
  },
  { "title": "Flag writer", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Input rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(katsdpcontroller_input_bytes_total{service=~\"flag_writer.*\",subarray_product_id=\"$sub\"}[$time]))"
    }
   ]
  },
  {
   "title": "Heaps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 24 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(katsdpcontroller_input_heaps_total{service=~\"flag_writer.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Good"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_incomplete_heaps_total{service=~\"flag_writer.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_missing_heaps_total{service=~\"flag_writer.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Missing"
    },
    {
     "expr": "sum(rate(katsdpcontroller_input_missing_heaps_total{service=~\"flag_writer.*\", subarray_product_id=\"$sub\"}[$time]))",
     "legendFormat": "Too old"
    }
   ]
  },
  {
   "title": "Write speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "delta(katsdpcontroller_output_bytes_total{service=~\"flag_writer\\\\..*\", subarray_product_id=\"$sub\"}[$time]) / delta(katsdpcontroller_output_seconds_total{service=~\"flag_writer\\\\..*\", subarray_product_id=\"$sub\"}[$time])",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "rate(katsdpcontroller_output_bytes_total{service=~\"flag_writer\\\\..*\", subarray_product_id=\"$sub\"}[$time])",
     "legendFormat": "{{service}} (overall)"
    }
   ]
  },
  {
   "title": "Signal display",
   "type": "text",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 30 },
   "content": "<style>\n.signal-display\n{\n  border: 0px;\n  margin: 0px;\n  padding: 0px;\n}\niframe.signal-display\n{\n  background-color: white;\n  width: 100%;\n  height: 100%;\n}\ndiv.signal-display\n{\n  height: 100%;\n}\np.signal-display\n{\n  display: block;\n  height: 100%;\n}\n</style>\n<script type=\"text/javascript\">\n$(\"div.signal-display\").parent().addClass(\"signal-display\");\n$(\"iframe.signal-display\").attr(\"src\", \"http://\" + window.location.hostname + \":5004/gui/$sub/timeplot.sdp_l0/signal-display/\");\n</script>\n<div class=\"signal-display\">\n  <iframe class=\"signal-display\" src=\"\">\n</div>"
  }
 ]
}